---
  - name: Creating MAC-VRF
    nokia.srlinux.config:
      update:
        - path: /network-instance[name=vrf-1]
          value:                                 
            name: vrf-1
            type: mac-vrf
            admin-state: enable
            interface:
            - name: ethernet-1/1.0
            vxlan-interface:
            - name: vxlan1.1
            protocols:
              bgp-evpn:
                bgp-instance:
                - id: 1
                  admin-state: enable
                  vxlan-interface: vxlan1.1
                  evi: 1
                  ecmp: 2
              bgp-vpn:
                bgp-instance:
                - id: 1
                  route-target:
                    export-rt: target:100:1
                    import-rt: target:100:1
