---
  - name: Creating VxLAN Tunnel
    nokia.srlinux.config:
      update:
        - path: /tunnel-interface[name=vxlan1]
          value:               
            name: vxlan1
            vxlan-interface:
            - index: 1
              type: bridged
              ingress:
                vni: 1