---
  - name: Execute "show version" CLI command
    nokia.srlinux.cli:
      commands:
        - enter candidate

        # configuration of the physical interface and its subinterface
        - set / interface ethernet-1/49
        - set / interface ethernet-1/49 subinterface 0
        - set / interface ethernet-1/49 subinterface 0 ipv4
        - set / interface ethernet-1/49 subinterface 0 ipv4 address 192.168.11.1/30

        # system interface configuration
        - set / interface system0
        - set / interface system0 admin-state enable
        - set / interface system0 subinterface 0
        - set / interface system0 subinterface 0 ipv4
        - set / interface system0 subinterface 0 ipv4 address 10.0.0.1/32

        # associating interfaces with net-ins default
        - set / network-instance default
        - set / network-instance default interface ethernet-1/49.0
        - set / network-instance default interface system0.0

        # routing policy
        - set / routing-policy
        - set / routing-policy policy all
        - set / routing-policy policy all default-action
        - set / routing-policy policy all default-action policy-result accept

        # BGP configuration
        - set / network-instance default protocols
        - set / network-instance default protocols bgp
        - set / network-instance default protocols bgp autonomous-system 101
        - set / network-instance default protocols bgp router-id 10.0.0.1
        - set / network-instance default protocols bgp group eBGP-underlay
        - set / network-instance default protocols bgp group eBGP-underlay export-policy all
        - set / network-instance default protocols bgp group eBGP-underlay import-policy all
        - set / network-instance default protocols bgp group eBGP-underlay peer-as 201
        - set / network-instance default protocols bgp ipv4-unicast
        - set / network-instance default protocols bgp ipv4-unicast admin-state enable
        - set / network-instance default protocols bgp neighbor 192.168.11.2
        - set / network-instance default protocols bgp neighbor 192.168.11.2 peer-group eBGP-underlay

        - commit now


  
  # - name: Get /system/information container
  #   nokia.srlinux.get:
  #     paths:
  #       - path: /system/information
  #         datastore: state
  #         yang_models: srl 
  #   register: response

  # - name: display resource
  #   debug:
  #     msg: |
  #       {{response}}



# ---
#   - name: Set system information with values
#     nokia.srlinux.config:
#       update:
#         - path: /system/information
#           value:
#             location: Nokia Data Center in Boston
#             contact: Mohammad Zaman
#     register: set_response



# ---
#   - name: collecting chassis info
#     nokia.srl.srl_command:
#       commands:
#         - show interface mgmt0
#         - show platform chassis

#     register: output

#   - name: display resource
#     debug:
#       msg: |
#         {{output}}
# ...
