
# updating the netbox with the inventory details of IP

# - hosts: nokia
#   gather_facts: false
#   tags: [ 'get_chassis_info' ]
#   roles:
#     - 'get_chassis_info'

# updating the netbox with the inventory details of IP

# - hosts: nokia
#   gather_facts: false
#   tags: [ 'build_topology' ]
#   roles:
#     - 'build_topology'


# #configuring the underlay-fabric

- hosts: leaf1
  gather_facts: false
  tags: [ 'leaf1_config']
  roles:
    - leaf1_config

# #configuring the evpn config

# - hosts: nokia
#   gather_facts: false
#   tags: [ 'deploy_evpn']
#   roles:
#     - deploy_evpn
